[colors]
foreground = "#e0e2e8"
background = "#1c2024"
cursor_bg = "#ffb0cd"
cursor_border = "#ffb0cd"
cursor_fg = "#1c2024"
selection_bg = "#5a3f49"
selection_fg = "#e0e2e8"

ansi = [
    "#1c2024",
    "#ffb0cd",
    "#a9d291",
    "#ecc06c",
    "#a7c8ff",
    "#e0b8f6",
    "#88d6ba",
    "#c0c7cd",
]

brights = [
    "#41484d",
    "#ffd9e4",
    "#c5efa7",
    "#ffdea4",
    "#d5e3ff",
    "#f4d9ff",
    "#a4f2d6",
    "#e0e2e8",
]

scrollbar_thumb = '#5a3f49'
split = '#8b9297'

[colors.indexed]

[colors.tab_bar]
background = '#1c2024'
inactive_tab_edge = '#8b9297'

[colors.tab_bar.active_tab]
bg_color = '#ffb0cd'
fg_color = '#531d36'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#1c2024'
fg_color = '#8b9297'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#e1bdc8'
fg_color = '#412932'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#1c2024'
fg_color = '#e0e2e8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#e1bdc8'
fg_color = '#412932'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'Crystar Z'
name = 'oneiroi melatonin'
