[colors]
foreground = "#e0e2e8"
background = "#25282c"
cursor_bg = "#ffb0cd"
cursor_border = "#ffb0cd"
cursor_fg = "#25282c"
selection_bg = "#713341"
selection_fg = "#e0e2e8"

ansi = [
    "#25282c",
    "#ffb0cd",
    "#aad291",
    "#edc06c",
    "#a6c8ff",
    "#e0b8f6",
    "#89d6b9",
    "#ecd7db",
]

brights = [
    "#9d8c90",
    "#ffd9e4",
    "#c5efa7",
    "#ffdea7",
    "#d5e3ff",
    "#f4daff",
    "#a4f2d5",
    "#e0e2e8",
]

scrollbar_thumb = '#713341'
split = '#c0adb1'

[colors.indexed]

[colors.tab_bar]
background = '#25282c'
inactive_tab_edge = '#c0adb1'

[colors.tab_bar.active_tab]
bg_color = '#ffb0cd'
fg_color = '#531d36'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = '#25282c'
fg_color = '#c0adb1'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#ffb1c0'
fg_color = '#551d2c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = '#25282c'
fg_color = '#e0e2e8'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = '#ffb1c0'
fg_color = '#551d2c'
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'Crystar Z'
name = 'oneiroi dream'
